//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18051
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTest.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwSiteDegree", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class vwSiteDegree : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CURRENT_DEGREEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSTOMER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENVIRONMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MAX_XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MAX_YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MIN_XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MIN_YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CURRENT_DEGREE {
            get {
                return this.CURRENT_DEGREEField;
            }
            set {
                this.CURRENT_DEGREEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                this.CUSTOMER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMER_NAME {
            get {
                return this.CUSTOMER_NAMEField;
            }
            set {
                this.CUSTOMER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENVIRONMENT {
            get {
                return this.ENVIRONMENTField;
            }
            set {
                this.ENVIRONMENTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MAX_X {
            get {
                return this.MAX_XField;
            }
            set {
                this.MAX_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MAX_Y {
            get {
                return this.MAX_YField;
            }
            set {
                this.MAX_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MIN_X {
            get {
                return this.MIN_XField;
            }
            set {
                this.MIN_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MIN_Y {
            get {
                return this.MIN_YField;
            }
            set {
                this.MIN_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ADDRESS {
            get {
                return this.SITE_ADDRESSField;
            }
            set {
                this.SITE_ADDRESSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_NAME {
            get {
                return this.SITE_NAMEField;
            }
            set {
                this.SITE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwSensorDegree", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class vwSensorDegree : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CURRENT_DEGREEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EXCUTION_MODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISCONNECTEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISVALIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MFCC_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SENSOR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENSOR_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENSOR_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CURRENT_DEGREE {
            get {
                return this.CURRENT_DEGREEField;
            }
            set {
                this.CURRENT_DEGREEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EXCUTION_MODE {
            get {
                return this.EXCUTION_MODEField;
            }
            set {
                this.EXCUTION_MODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISCONNECTED {
            get {
                return this.ISCONNECTEDField;
            }
            set {
                this.ISCONNECTEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISVALID {
            get {
                return this.ISVALIDField;
            }
            set {
                this.ISVALIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsConfirmed {
            get {
                return this.IsConfirmedField;
            }
            set {
                this.IsConfirmedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MFCC_ID {
            get {
                return this.MFCC_IDField;
            }
            set {
                this.MFCC_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SENSOR_ID {
            get {
                return this.SENSOR_IDField;
            }
            set {
                this.SENSOR_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENSOR_NAME {
            get {
                return this.SENSOR_NAMEField;
            }
            set {
                this.SENSOR_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENSOR_TYPE {
            get {
                return this.SENSOR_TYPEField;
            }
            set {
                this.SENSOR_TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE0 {
            get {
                return this.VALUE0Field;
            }
            set {
                this.VALUE0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE1 {
            get {
                return this.VALUE1Field;
            }
            set {
                this.VALUE1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE2 {
            get {
                return this.VALUE2Field;
            }
            set {
                this.VALUE2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> X {
            get {
                return this.XField;
            }
            set {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Y {
            get {
                return this.YField;
            }
            set {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCCTV", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblCCTV : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCTV_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REF_CCTV_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ROTATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblSite tblSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblSite> tblSiteReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCTV_ID {
            get {
                return this.CCTV_IDField;
            }
            set {
                this.CCTV_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                this.DESCRIPTIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REF_CCTV_ID {
            get {
                return this.REF_CCTV_IDField;
            }
            set {
                this.REF_CCTV_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ROTATION {
            get {
                return this.ROTATIONField;
            }
            set {
                this.ROTATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> X {
            get {
                return this.XField;
            }
            set {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Y {
            get {
                return this.YField;
            }
            set {
                this.YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblSite tblSite {
            get {
                return this.tblSiteField;
            }
            set {
                this.tblSiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblSite> tblSiteReference {
            get {
                return this.tblSiteReferenceField;
            }
            set {
                this.tblSiteReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblSite", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblSite : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AREA_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BUILDING_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRACT_STARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRACT_TERMINATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COUNTY_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTROMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENGINEERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENVIRONMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MAX_XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MAX_YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MIN_XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MIN_YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N3_CONTENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> ON_STORIEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> STRUCT_TYPE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> UNDER_STORIEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblCCTV[] tblCCTVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblCustomer tblCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblCustomer> tblCustomerReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AREA_ID {
            get {
                return this.AREA_IDField;
            }
            set {
                this.AREA_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BUILDING_TYPE_ID {
            get {
                return this.BUILDING_TYPE_IDField;
            }
            set {
                this.BUILDING_TYPE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRACT_START {
            get {
                return this.CONTRACT_STARTField;
            }
            set {
                this.CONTRACT_STARTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRACT_TERMINATION {
            get {
                return this.CONTRACT_TERMINATIONField;
            }
            set {
                this.CONTRACT_TERMINATIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COUNTY_ID {
            get {
                return this.COUNTY_IDField;
            }
            set {
                this.COUNTY_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTROMER_ID {
            get {
                return this.CUSTROMER_IDField;
            }
            set {
                this.CUSTROMER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENGINEER {
            get {
                return this.ENGINEERField;
            }
            set {
                this.ENGINEERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENVIRONMENT {
            get {
                return this.ENVIRONMENTField;
            }
            set {
                this.ENVIRONMENTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAX {
            get {
                return this.FAXField;
            }
            set {
                this.FAXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MAX_X {
            get {
                return this.MAX_XField;
            }
            set {
                this.MAX_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MAX_Y {
            get {
                return this.MAX_YField;
            }
            set {
                this.MAX_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MIN_X {
            get {
                return this.MIN_XField;
            }
            set {
                this.MIN_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MIN_Y {
            get {
                return this.MIN_YField;
            }
            set {
                this.MIN_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N3_CONTENT {
            get {
                return this.N3_CONTENTField;
            }
            set {
                this.N3_CONTENTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> ON_STORIED {
            get {
                return this.ON_STORIEDField;
            }
            set {
                this.ON_STORIEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ADDRESS {
            get {
                return this.SITE_ADDRESSField;
            }
            set {
                this.SITE_ADDRESSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_NAME {
            get {
                return this.SITE_NAMEField;
            }
            set {
                this.SITE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_NO {
            get {
                return this.SITE_NOField;
            }
            set {
                this.SITE_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> STRUCT_TYPE_ID {
            get {
                return this.STRUCT_TYPE_IDField;
            }
            set {
                this.STRUCT_TYPE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> UNDER_STORIED {
            get {
                return this.UNDER_STORIEDField;
            }
            set {
                this.UNDER_STORIEDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                this.YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblCCTV[] tblCCTV {
            get {
                return this.tblCCTVField;
            }
            set {
                this.tblCCTVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblCustomer tblCustomer {
            get {
                return this.tblCustomerField;
            }
            set {
                this.tblCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblCustomer> tblCustomerReference {
            get {
                return this.tblCustomerReferenceField;
            }
            set {
                this.tblCustomerReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblCustomer", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblCustomer : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSTOMER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUB_CUSTOMER_IDSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEPHONEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblSite[] tblSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblUser[] tblUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRESS {
            get {
                return this.ADDRESSField;
            }
            set {
                this.ADDRESSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                this.CUSTOMER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUSTOMER_NAME {
            get {
                return this.CUSTOMER_NAMEField;
            }
            set {
                this.CUSTOMER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAIL {
            get {
                return this.MAILField;
            }
            set {
                this.MAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUB_CUSTOMER_IDS {
            get {
                return this.SUB_CUSTOMER_IDSField;
            }
            set {
                this.SUB_CUSTOMER_IDSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEPHONE {
            get {
                return this.TELEPHONEField;
            }
            set {
                this.TELEPHONEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblSite[] tblSite {
            get {
                return this.tblSiteField;
            }
            set {
                this.tblSiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblUser[] tblUser {
            get {
                return this.tblUserField;
            }
            set {
                this.tblUserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblUser", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblUser : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CUSTOMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ROLESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEPHONEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URI_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_MAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_PWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientTest.DataService.tblCustomer tblCustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblCustomer> tblCustomerReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CUSTOMER_ID {
            get {
                return this.CUSTOMER_IDField;
            }
            set {
                this.CUSTOMER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAX {
            get {
                return this.FAXField;
            }
            set {
                this.FAXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOBLE {
            get {
                return this.MOBLEField;
            }
            set {
                this.MOBLEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ROLES {
            get {
                return this.ROLESField;
            }
            set {
                this.ROLESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEPHONE {
            get {
                return this.TELEPHONEField;
            }
            set {
                this.TELEPHONEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URI_CODE {
            get {
                return this.URI_CODEField;
            }
            set {
                this.URI_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ADDRESS {
            get {
                return this.USER_ADDRESSField;
            }
            set {
                this.USER_ADDRESSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                this.USER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_MAIL {
            get {
                return this.USER_MAILField;
            }
            set {
                this.USER_MAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_NAME {
            get {
                return this.USER_NAMEField;
            }
            set {
                this.USER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_PW {
            get {
                return this.USER_PWField;
            }
            set {
                this.USER_PWField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientTest.DataService.tblCustomer tblCustomer {
            get {
                return this.tblCustomerField;
            }
            set {
                this.tblCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<ClientTest.DataService.tblCustomer> tblCustomerReference {
            get {
                return this.tblCustomerReferenceField;
            }
            set {
                this.tblCustomerReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblPre_disasterNotified", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblPre_disasterNotified : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AFTER_TIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISASTER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDENTIFIED_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte ISREPORTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISSENDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NOTIFIED_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRE_ADMONISH_CLASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PRE_TIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PUBLISH_ORANGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITLEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AFTER_TIMESTAMP {
            get {
                return this.AFTER_TIMESTAMPField;
            }
            set {
                this.AFTER_TIMESTAMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTENT {
            get {
                return this.CONTENTField;
            }
            set {
                this.CONTENTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DISASTER_NAME {
            get {
                return this.DISASTER_NAMEField;
            }
            set {
                this.DISASTER_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDENTIFIED_ID {
            get {
                return this.IDENTIFIED_IDField;
            }
            set {
                this.IDENTIFIED_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte ISREPORT {
            get {
                return this.ISREPORTField;
            }
            set {
                this.ISREPORTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISSEND {
            get {
                return this.ISSENDField;
            }
            set {
                this.ISSENDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NOTIFIED_TIME {
            get {
                return this.NOTIFIED_TIMEField;
            }
            set {
                this.NOTIFIED_TIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRE_ADMONISH_CLASS {
            get {
                return this.PRE_ADMONISH_CLASSField;
            }
            set {
                this.PRE_ADMONISH_CLASSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PRE_TIMESTAMP {
            get {
                return this.PRE_TIMESTAMPField;
            }
            set {
                this.PRE_TIMESTAMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PUBLISH_ORANG {
            get {
                return this.PUBLISH_ORANGField;
            }
            set {
                this.PUBLISH_ORANGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TIMESTAMP {
            get {
                return this.TIMESTAMPField;
            }
            set {
                this.TIMESTAMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITLE {
            get {
                return this.TITLEField;
            }
            set {
                this.TITLEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblSurvey_Disaster", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class tblSurvey_Disaster : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BUILD_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUILD_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CASUALTIES_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CASUALTIES_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CASUALTIES_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CASUALTIES_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DAMAGED_BRIDGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DAMAGED_BRIDGE_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DAMAGED_ROADSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DAMAGED_ROADS_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EVACUATION_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EVACUATION_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ISCHECKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ISCLOSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string N3_REPORT_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OCCUR_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHOTO_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLACE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SITUATION_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte SITUATION_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SITUATION_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TYPE_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> USER__POSITION_XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> USER__POSITION_YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BUILD_TIME {
            get {
                return this.BUILD_TIMEField;
            }
            set {
                this.BUILD_TIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUILD_USER {
            get {
                return this.BUILD_USERField;
            }
            set {
                this.BUILD_USERField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CASUALTIES_0 {
            get {
                return this.CASUALTIES_0Field;
            }
            set {
                this.CASUALTIES_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CASUALTIES_1 {
            get {
                return this.CASUALTIES_1Field;
            }
            set {
                this.CASUALTIES_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CASUALTIES_2 {
            get {
                return this.CASUALTIES_2Field;
            }
            set {
                this.CASUALTIES_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CASUALTIES_3 {
            get {
                return this.CASUALTIES_3Field;
            }
            set {
                this.CASUALTIES_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DAMAGED_BRIDGE {
            get {
                return this.DAMAGED_BRIDGEField;
            }
            set {
                this.DAMAGED_BRIDGEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DAMAGED_BRIDGE_0 {
            get {
                return this.DAMAGED_BRIDGE_0Field;
            }
            set {
                this.DAMAGED_BRIDGE_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DAMAGED_ROADS {
            get {
                return this.DAMAGED_ROADSField;
            }
            set {
                this.DAMAGED_ROADSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DAMAGED_ROADS_0 {
            get {
                return this.DAMAGED_ROADS_0Field;
            }
            set {
                this.DAMAGED_ROADS_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EVACUATION_0 {
            get {
                return this.EVACUATION_0Field;
            }
            set {
                this.EVACUATION_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EVACUATION_1 {
            get {
                return this.EVACUATION_1Field;
            }
            set {
                this.EVACUATION_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ISCHECK {
            get {
                return this.ISCHECKField;
            }
            set {
                this.ISCHECKField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ISCLOSE {
            get {
                return this.ISCLOSEField;
            }
            set {
                this.ISCLOSEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string N3_REPORT_ID {
            get {
                return this.N3_REPORT_IDField;
            }
            set {
                this.N3_REPORT_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OCCUR_TIME {
            get {
                return this.OCCUR_TIMEField;
            }
            set {
                this.OCCUR_TIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHOTO_PATH {
            get {
                return this.PHOTO_PATHField;
            }
            set {
                this.PHOTO_PATHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLACE_NAME {
            get {
                return this.PLACE_NAMEField;
            }
            set {
                this.PLACE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SITUATION_0 {
            get {
                return this.SITUATION_0Field;
            }
            set {
                this.SITUATION_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SITUATION_1 {
            get {
                return this.SITUATION_1Field;
            }
            set {
                this.SITUATION_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SITUATION_2 {
            get {
                return this.SITUATION_2Field;
            }
            set {
                this.SITUATION_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_0 {
            get {
                return this.TYPE_0Field;
            }
            set {
                this.TYPE_0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_1 {
            get {
                return this.TYPE_1Field;
            }
            set {
                this.TYPE_1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_2 {
            get {
                return this.TYPE_2Field;
            }
            set {
                this.TYPE_2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_3 {
            get {
                return this.TYPE_3Field;
            }
            set {
                this.TYPE_3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_4 {
            get {
                return this.TYPE_4Field;
            }
            set {
                this.TYPE_4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_5 {
            get {
                return this.TYPE_5Field;
            }
            set {
                this.TYPE_5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TYPE_6 {
            get {
                return this.TYPE_6Field;
            }
            set {
                this.TYPE_6Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> USER__POSITION_X {
            get {
                return this.USER__POSITION_XField;
            }
            set {
                this.USER__POSITION_XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> USER__POSITION_Y {
            get {
                return this.USER__POSITION_YField;
            }
            set {
                this.USER__POSITION_YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> X {
            get {
                return this.XField;
            }
            set {
                this.XField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Y {
            get {
                return this.YField;
            }
            set {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwReportNotified", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class vwReportNotified : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CUSTROMER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DATATIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ISTOBAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SITE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CUSTROMER_ID {
            get {
                return this.CUSTROMER_IDField;
            }
            set {
                this.CUSTROMER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATATIME {
            get {
                return this.DATATIMEField;
            }
            set {
                this.DATATIMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ISTOBA {
            get {
                return this.ISTOBAField;
            }
            set {
                this.ISTOBAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_ID {
            get {
                return this.SITE_IDField;
            }
            set {
                this.SITE_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SITE_NAME {
            get {
                return this.SITE_NAMEField;
            }
            set {
                this.SITE_NAMEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                this.TYPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                this.URLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwSensorValuesAndTC10MinDataLog", Namespace="http://schemas.datacontract.org/2004/07/DataService", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class vwSensorValuesAndTC10MinDataLog : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CONTROLLER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte DEGREEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EXECUTION_MODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISVALIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IS_REPAIRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SENSOR_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TIMESTAMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> VALUE2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> VALUE_CNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double initmean0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double initmean1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double initmean2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sigma1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sigma2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double signama0Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CONTROLLER_ID {
            get {
                return this.CONTROLLER_IDField;
            }
            set {
                this.CONTROLLER_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte DEGREE {
            get {
                return this.DEGREEField;
            }
            set {
                this.DEGREEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EXECUTION_MODE {
            get {
                return this.EXECUTION_MODEField;
            }
            set {
                this.EXECUTION_MODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISVALID {
            get {
                return this.ISVALIDField;
            }
            set {
                this.ISVALIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IS_REPAIR {
            get {
                return this.IS_REPAIRField;
            }
            set {
                this.IS_REPAIRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SENSOR_ID {
            get {
                return this.SENSOR_IDField;
            }
            set {
                this.SENSOR_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TIMESTAMP {
            get {
                return this.TIMESTAMPField;
            }
            set {
                this.TIMESTAMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE0 {
            get {
                return this.VALUE0Field;
            }
            set {
                this.VALUE0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE1 {
            get {
                return this.VALUE1Field;
            }
            set {
                this.VALUE1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> VALUE2 {
            get {
                return this.VALUE2Field;
            }
            set {
                this.VALUE2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> VALUE_CNT {
            get {
                return this.VALUE_CNTField;
            }
            set {
                this.VALUE_CNTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double initmean0 {
            get {
                return this.initmean0Field;
            }
            set {
                this.initmean0Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double initmean1 {
            get {
                return this.initmean1Field;
            }
            set {
                this.initmean1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double initmean2 {
            get {
                return this.initmean2Field;
            }
            set {
                this.initmean2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sigma1 {
            get {
                return this.sigma1Field;
            }
            set {
                this.sigma1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sigma2 {
            get {
                return this.sigma2Field;
            }
            set {
                this.sigma2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double signama0 {
            get {
                return this.signama0Field;
            }
            set {
                this.signama0Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.ISSHMCDataService")]
    public interface ISSHMCDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/CheckUserIDPassword", ReplyAction="http://tempuri.org/ISSHMCDataService/CheckUserIDPasswordResponse")]
        bool CheckUserIDPassword(string id, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetSiteInfo", ReplyAction="http://tempuri.org/ISSHMCDataService/GetSiteInfoResponse")]
        ClientTest.DataService.vwSiteDegree[] GetSiteInfo(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetSensorInfo", ReplyAction="http://tempuri.org/ISSHMCDataService/GetSensorInfoResponse")]
        ClientTest.DataService.vwSensorDegree[] GetSensorInfo(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetCCTVInfo", ReplyAction="http://tempuri.org/ISSHMCDataService/GetCCTVInfoResponse")]
        ClientTest.DataService.tblCCTV[] GetCCTVInfo(string SiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetDisasterInfo", ReplyAction="http://tempuri.org/ISSHMCDataService/GetDisasterInfoResponse")]
        ClientTest.DataService.tblPre_disasterNotified[] GetDisasterInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetSurveyDisaster", ReplyAction="http://tempuri.org/ISSHMCDataService/GetSurveyDisasterResponse")]
        ClientTest.DataService.tblSurvey_Disaster[] GetSurveyDisaster();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/AddSurverDiasterInfo", ReplyAction="http://tempuri.org/ISSHMCDataService/AddSurverDiasterInfoResponse")]
        string AddSurverDiasterInfo(ClientTest.DataService.tblSurvey_Disaster info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GettblReportNotified", ReplyAction="http://tempuri.org/ISSHMCDataService/GettblReportNotifiedResponse")]
        ClientTest.DataService.vwReportNotified[] GettblReportNotified(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSHMCDataService/GetvwSensorValuesAndTC10MinDataLog", ReplyAction="http://tempuri.org/ISSHMCDataService/GetvwSensorValuesAndTC10MinDataLogResponse")]
        ClientTest.DataService.vwSensorValuesAndTC10MinDataLog[] GetvwSensorValuesAndTC10MinDataLog(int snrid, System.DateTime StartDate, System.DateTime EndDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISSHMCDataServiceChannel : ClientTest.DataService.ISSHMCDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSHMCDataServiceClient : System.ServiceModel.ClientBase<ClientTest.DataService.ISSHMCDataService>, ClientTest.DataService.ISSHMCDataService {
        
        public SSHMCDataServiceClient() {
        }
        
        public SSHMCDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSHMCDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSHMCDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSHMCDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckUserIDPassword(string id, string Password) {
            return base.Channel.CheckUserIDPassword(id, Password);
        }
        
        public ClientTest.DataService.vwSiteDegree[] GetSiteInfo(string id) {
            return base.Channel.GetSiteInfo(id);
        }
        
        public ClientTest.DataService.vwSensorDegree[] GetSensorInfo(string SiteID) {
            return base.Channel.GetSensorInfo(SiteID);
        }
        
        public ClientTest.DataService.tblCCTV[] GetCCTVInfo(string SiteID) {
            return base.Channel.GetCCTVInfo(SiteID);
        }
        
        public ClientTest.DataService.tblPre_disasterNotified[] GetDisasterInfo() {
            return base.Channel.GetDisasterInfo();
        }
        
        public ClientTest.DataService.tblSurvey_Disaster[] GetSurveyDisaster() {
            return base.Channel.GetSurveyDisaster();
        }
        
        public string AddSurverDiasterInfo(ClientTest.DataService.tblSurvey_Disaster info) {
            return base.Channel.AddSurverDiasterInfo(info);
        }
        
        public ClientTest.DataService.vwReportNotified[] GettblReportNotified(string userid) {
            return base.Channel.GettblReportNotified(userid);
        }
        
        public ClientTest.DataService.vwSensorValuesAndTC10MinDataLog[] GetvwSensorValuesAndTC10MinDataLog(int snrid, System.DateTime StartDate, System.DateTime EndDate) {
            return base.Channel.GetvwSensorValuesAndTC10MinDataLog(snrid, StartDate, EndDate);
        }
    }
}
