//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace slStatusMoniter.Web
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class SSCMEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'SSCMEntities' 區段中找到的連接字串，初始化新的 SSCMEntities 物件。
        /// </summary>
        public SSCMEntities() : base("name=SSCMEntities", "SSCMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSCMEntities 物件。
        /// </summary>
        public SSCMEntities(string connectionString) : base(connectionString, "SSCMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSCMEntities 物件。
        /// </summary>
        public SSCMEntities(EntityConnection connection) : base(connection, "SSCMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwSensorStatus> vwSensorStatus
        {
            get
            {
                if ((_vwSensorStatus == null))
                {
                    _vwSensorStatus = base.CreateObjectSet<vwSensorStatus>("vwSensorStatus");
                }
                return _vwSensorStatus;
            }
        }
        private ObjectSet<vwSensorStatus> _vwSensorStatus;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 vwSensorStatus EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwSensorStatus(vwSensorStatus vwSensorStatus)
        {
            base.AddObject("vwSensorStatus", vwSensorStatus);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSCMModel", Name="vwSensorStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwSensorStatus : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwSensorStatus 物件。
        /// </summary>
        /// <param name="pNO">PNO 屬性的初始值。</param>
        /// <param name="cX">CX 屬性的初始值。</param>
        /// <param name="cY">CY 屬性的初始值。</param>
        /// <param name="pICTYPE">PICTYPE 屬性的初始值。</param>
        /// <param name="lEVEL">LEVEL 屬性的初始值。</param>
        public static vwSensorStatus CreatevwSensorStatus(global::System.String pNO, global::System.String cX, global::System.String cY, global::System.String pICTYPE, global::System.Int32 lEVEL)
        {
            vwSensorStatus vwSensorStatus = new vwSensorStatus();
            vwSensorStatus.PNO = pNO;
            vwSensorStatus.CX = cX;
            vwSensorStatus.CY = cY;
            vwSensorStatus.PICTYPE = pICTYPE;
            vwSensorStatus.LEVEL = lEVEL;
            return vwSensorStatus;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PNO
        {
            get
            {
                return _PNO;
            }
            set
            {
                if (_PNO != value)
                {
                    OnPNOChanging(value);
                    ReportPropertyChanging("PNO");
                    _PNO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PNO");
                    OnPNOChanged();
                }
            }
        }
        private global::System.String _PNO;
        partial void OnPNOChanging(global::System.String value);
        partial void OnPNOChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CX
        {
            get
            {
                return _CX;
            }
            set
            {
                if (_CX != value)
                {
                    OnCXChanging(value);
                    ReportPropertyChanging("CX");
                    _CX = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CX");
                    OnCXChanged();
                }
            }
        }
        private global::System.String _CX;
        partial void OnCXChanging(global::System.String value);
        partial void OnCXChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CY
        {
            get
            {
                return _CY;
            }
            set
            {
                if (_CY != value)
                {
                    OnCYChanging(value);
                    ReportPropertyChanging("CY");
                    _CY = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CY");
                    OnCYChanged();
                }
            }
        }
        private global::System.String _CY;
        partial void OnCYChanging(global::System.String value);
        partial void OnCYChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PICTYPE
        {
            get
            {
                return _PICTYPE;
            }
            set
            {
                if (_PICTYPE != value)
                {
                    OnPICTYPEChanging(value);
                    ReportPropertyChanging("PICTYPE");
                    _PICTYPE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PICTYPE");
                    OnPICTYPEChanged();
                }
            }
        }
        private global::System.String _PICTYPE;
        partial void OnPICTYPEChanging(global::System.String value);
        partial void OnPICTYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LEVEL
        {
            get
            {
                return _LEVEL;
            }
            set
            {
                if (_LEVEL != value)
                {
                    OnLEVELChanging(value);
                    ReportPropertyChanging("LEVEL");
                    _LEVEL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LEVEL");
                    OnLEVELChanged();
                }
            }
        }
        private global::System.Int32 _LEVEL;
        partial void OnLEVELChanging(global::System.Int32 value);
        partial void OnLEVELChanged();

        #endregion
    
    }

    #endregion
    
}
