//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MFCC_BA
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class SSHMC01Entities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'SSHMC01Entities' 區段中找到的連接字串，初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities() : base("name=SSHMC01Entities", "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities(string connectionString) : base(connectionString, "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities(EntityConnection connection) : base(connection, "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblTC> tblTC
        {
            get
            {
                if ((_tblTC == null))
                {
                    _tblTC = base.CreateObjectSet<tblTC>("tblTC");
                }
                return _tblTC;
            }
        }
        private ObjectSet<tblTC> _tblTC;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwSensorDegree> vwSensorDegree
        {
            get
            {
                if ((_vwSensorDegree == null))
                {
                    _vwSensorDegree = base.CreateObjectSet<vwSensorDegree>("vwSensorDegree");
                }
                return _vwSensorDegree;
            }
        }
        private ObjectSet<vwSensorDegree> _vwSensorDegree;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwSiteToBA_Status> vwSiteToBA_Status
        {
            get
            {
                if ((_vwSiteToBA_Status == null))
                {
                    _vwSiteToBA_Status = base.CreateObjectSet<vwSiteToBA_Status>("vwSiteToBA_Status");
                }
                return _vwSiteToBA_Status;
            }
        }
        private ObjectSet<vwSiteToBA_Status> _vwSiteToBA_Status;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<vwSiteToBA_Report> vwSiteToBA_Report
        {
            get
            {
                if ((_vwSiteToBA_Report == null))
                {
                    _vwSiteToBA_Report = base.CreateObjectSet<vwSiteToBA_Report>("vwSiteToBA_Report");
                }
                return _vwSiteToBA_Report;
            }
        }
        private ObjectSet<vwSiteToBA_Report> _vwSiteToBA_Report;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblReportNotified> tblReportNotified
        {
            get
            {
                if ((_tblReportNotified == null))
                {
                    _tblReportNotified = base.CreateObjectSet<tblReportNotified>("tblReportNotified");
                }
                return _tblReportNotified;
            }
        }
        private ObjectSet<tblReportNotified> _tblReportNotified;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblTC EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblTC(tblTC tblTC)
        {
            base.AddObject("tblTC", tblTC);
        }
    
        /// <summary>
        /// 將新物件加入 vwSensorDegree EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwSensorDegree(vwSensorDegree vwSensorDegree)
        {
            base.AddObject("vwSensorDegree", vwSensorDegree);
        }
    
        /// <summary>
        /// 將新物件加入 vwSiteToBA_Status EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwSiteToBA_Status(vwSiteToBA_Status vwSiteToBA_Status)
        {
            base.AddObject("vwSiteToBA_Status", vwSiteToBA_Status);
        }
    
        /// <summary>
        /// 將新物件加入 vwSiteToBA_Report EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTovwSiteToBA_Report(vwSiteToBA_Report vwSiteToBA_Report)
        {
            base.AddObject("vwSiteToBA_Report", vwSiteToBA_Report);
        }
    
        /// <summary>
        /// 將新物件加入 tblReportNotified EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblReportNotified(tblReportNotified tblReportNotified)
        {
            base.AddObject("tblReportNotified", tblReportNotified);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="tblReportNotified")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblReportNotified : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblReportNotified 物件。
        /// </summary>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="dATATIME">DATATIME 屬性的初始值。</param>
        /// <param name="tYPE">TYPE 屬性的初始值。</param>
        /// <param name="uRL">URL 屬性的初始值。</param>
        public static tblReportNotified CreatetblReportNotified(global::System.String sITE_ID, global::System.DateTime dATATIME, global::System.String tYPE, global::System.String uRL)
        {
            tblReportNotified tblReportNotified = new tblReportNotified();
            tblReportNotified.SITE_ID = sITE_ID;
            tblReportNotified.DATATIME = dATATIME;
            tblReportNotified.TYPE = tYPE;
            tblReportNotified.URL = uRL;
            return tblReportNotified;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                if (_SITE_ID != value)
                {
                    OnSITE_IDChanging(value);
                    ReportPropertyChanging("SITE_ID");
                    _SITE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SITE_ID");
                    OnSITE_IDChanged();
                }
            }
        }
        private global::System.String _SITE_ID;
        partial void OnSITE_IDChanging(global::System.String value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATATIME
        {
            get
            {
                return _DATATIME;
            }
            set
            {
                if (_DATATIME != value)
                {
                    OnDATATIMEChanging(value);
                    ReportPropertyChanging("DATATIME");
                    _DATATIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DATATIME");
                    OnDATATIMEChanged();
                }
            }
        }
        private global::System.DateTime _DATATIME;
        partial void OnDATATIMEChanging(global::System.DateTime value);
        partial void OnDATATIMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    OnTYPEChanging(value);
                    ReportPropertyChanging("TYPE");
                    _TYPE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TYPE");
                    OnTYPEChanged();
                }
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ISTOBA
        {
            get
            {
                return _ISTOBA;
            }
            set
            {
                OnISTOBAChanging(value);
                ReportPropertyChanging("ISTOBA");
                _ISTOBA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISTOBA");
                OnISTOBAChanged();
            }
        }
        private Nullable<global::System.Boolean> _ISTOBA;
        partial void OnISTOBAChanging(Nullable<global::System.Boolean> value);
        partial void OnISTOBAChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="tblTC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTC : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblTC 物件。
        /// </summary>
        /// <param name="cONTROLLER_ID">CONTROLLER_ID 屬性的初始值。</param>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="mFCC_ID">MFCC_ID 屬性的初始值。</param>
        /// <param name="iSCONNECTED">ISCONNECTED 屬性的初始值。</param>
        /// <param name="iP">IP 屬性的初始值。</param>
        /// <param name="pORT">PORT 屬性的初始值。</param>
        /// <param name="hW_STATUS_1">HW_STATUS_1 屬性的初始值。</param>
        /// <param name="hW_STATUS_2">HW_STATUS_2 屬性的初始值。</param>
        /// <param name="hW_STATUS_3">HW_STATUS_3 屬性的初始值。</param>
        /// <param name="hW_STATUS_4">HW_STATUS_4 屬性的初始值。</param>
        /// <param name="eNABLE">ENABLE 屬性的初始值。</param>
        public static tblTC CreatetblTC(global::System.Int32 cONTROLLER_ID, global::System.String sITE_ID, global::System.String mFCC_ID, global::System.String iSCONNECTED, global::System.String iP, global::System.Int32 pORT, global::System.Byte hW_STATUS_1, global::System.Byte hW_STATUS_2, global::System.Byte hW_STATUS_3, global::System.Byte hW_STATUS_4, global::System.String eNABLE)
        {
            tblTC tblTC = new tblTC();
            tblTC.CONTROLLER_ID = cONTROLLER_ID;
            tblTC.SITE_ID = sITE_ID;
            tblTC.MFCC_ID = mFCC_ID;
            tblTC.ISCONNECTED = iSCONNECTED;
            tblTC.IP = iP;
            tblTC.PORT = pORT;
            tblTC.HW_STATUS_1 = hW_STATUS_1;
            tblTC.HW_STATUS_2 = hW_STATUS_2;
            tblTC.HW_STATUS_3 = hW_STATUS_3;
            tblTC.HW_STATUS_4 = hW_STATUS_4;
            tblTC.ENABLE = eNABLE;
            return tblTC;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTROLLER_ID
        {
            get
            {
                return _CONTROLLER_ID;
            }
            set
            {
                if (_CONTROLLER_ID != value)
                {
                    OnCONTROLLER_IDChanging(value);
                    ReportPropertyChanging("CONTROLLER_ID");
                    _CONTROLLER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CONTROLLER_ID");
                    OnCONTROLLER_IDChanged();
                }
            }
        }
        private global::System.Int32 _CONTROLLER_ID;
        partial void OnCONTROLLER_IDChanging(global::System.Int32 value);
        partial void OnCONTROLLER_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                OnSITE_IDChanging(value);
                ReportPropertyChanging("SITE_ID");
                _SITE_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SITE_ID");
                OnSITE_IDChanged();
            }
        }
        private global::System.String _SITE_ID;
        partial void OnSITE_IDChanging(global::System.String value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MFCC_ID
        {
            get
            {
                return _MFCC_ID;
            }
            set
            {
                OnMFCC_IDChanging(value);
                ReportPropertyChanging("MFCC_ID");
                _MFCC_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MFCC_ID");
                OnMFCC_IDChanged();
            }
        }
        private global::System.String _MFCC_ID;
        partial void OnMFCC_IDChanging(global::System.String value);
        partial void OnMFCC_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISCONNECTED
        {
            get
            {
                return _ISCONNECTED;
            }
            set
            {
                OnISCONNECTEDChanging(value);
                ReportPropertyChanging("ISCONNECTED");
                _ISCONNECTED = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ISCONNECTED");
                OnISCONNECTEDChanged();
            }
        }
        private global::System.String _ISCONNECTED;
        partial void OnISCONNECTEDChanging(global::System.String value);
        partial void OnISCONNECTEDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PORT
        {
            get
            {
                return _PORT;
            }
            set
            {
                OnPORTChanging(value);
                ReportPropertyChanging("PORT");
                _PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PORT");
                OnPORTChanged();
            }
        }
        private global::System.Int32 _PORT;
        partial void OnPORTChanging(global::System.Int32 value);
        partial void OnPORTChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEVICE_TYPE
        {
            get
            {
                return _DEVICE_TYPE;
            }
            set
            {
                OnDEVICE_TYPEChanging(value);
                ReportPropertyChanging("DEVICE_TYPE");
                _DEVICE_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEVICE_TYPE");
                OnDEVICE_TYPEChanged();
            }
        }
        private global::System.String _DEVICE_TYPE;
        partial void OnDEVICE_TYPEChanging(global::System.String value);
        partial void OnDEVICE_TYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BUILD_DATE
        {
            get
            {
                return _BUILD_DATE;
            }
            set
            {
                OnBUILD_DATEChanging(value);
                ReportPropertyChanging("BUILD_DATE");
                _BUILD_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BUILD_DATE");
                OnBUILD_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _BUILD_DATE;
        partial void OnBUILD_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnBUILD_DATEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION_NO
        {
            get
            {
                return _VERSION_NO;
            }
            set
            {
                OnVERSION_NOChanging(value);
                ReportPropertyChanging("VERSION_NO");
                _VERSION_NO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION_NO");
                OnVERSION_NOChanged();
            }
        }
        private global::System.String _VERSION_NO;
        partial void OnVERSION_NOChanging(global::System.String value);
        partial void OnVERSION_NOChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte HW_STATUS_1
        {
            get
            {
                return _HW_STATUS_1;
            }
            set
            {
                OnHW_STATUS_1Changing(value);
                ReportPropertyChanging("HW_STATUS_1");
                _HW_STATUS_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HW_STATUS_1");
                OnHW_STATUS_1Changed();
            }
        }
        private global::System.Byte _HW_STATUS_1;
        partial void OnHW_STATUS_1Changing(global::System.Byte value);
        partial void OnHW_STATUS_1Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte HW_STATUS_2
        {
            get
            {
                return _HW_STATUS_2;
            }
            set
            {
                OnHW_STATUS_2Changing(value);
                ReportPropertyChanging("HW_STATUS_2");
                _HW_STATUS_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HW_STATUS_2");
                OnHW_STATUS_2Changed();
            }
        }
        private global::System.Byte _HW_STATUS_2;
        partial void OnHW_STATUS_2Changing(global::System.Byte value);
        partial void OnHW_STATUS_2Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte HW_STATUS_3
        {
            get
            {
                return _HW_STATUS_3;
            }
            set
            {
                OnHW_STATUS_3Changing(value);
                ReportPropertyChanging("HW_STATUS_3");
                _HW_STATUS_3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HW_STATUS_3");
                OnHW_STATUS_3Changed();
            }
        }
        private global::System.Byte _HW_STATUS_3;
        partial void OnHW_STATUS_3Changing(global::System.Byte value);
        partial void OnHW_STATUS_3Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte HW_STATUS_4
        {
            get
            {
                return _HW_STATUS_4;
            }
            set
            {
                OnHW_STATUS_4Changing(value);
                ReportPropertyChanging("HW_STATUS_4");
                _HW_STATUS_4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HW_STATUS_4");
                OnHW_STATUS_4Changed();
            }
        }
        private global::System.Byte _HW_STATUS_4;
        partial void OnHW_STATUS_4Changing(global::System.Byte value);
        partial void OnHW_STATUS_4Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ENABLE
        {
            get
            {
                return _ENABLE;
            }
            set
            {
                OnENABLEChanging(value);
                ReportPropertyChanging("ENABLE");
                _ENABLE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ENABLE");
                OnENABLEChanged();
            }
        }
        private global::System.String _ENABLE;
        partial void OnENABLEChanging(global::System.String value);
        partial void OnENABLEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INTERNALL_IP
        {
            get
            {
                return _INTERNALL_IP;
            }
            set
            {
                OnINTERNALL_IPChanging(value);
                ReportPropertyChanging("INTERNALL_IP");
                _INTERNALL_IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INTERNALL_IP");
                OnINTERNALL_IPChanged();
            }
        }
        private global::System.String _INTERNALL_IP;
        partial void OnINTERNALL_IPChanging(global::System.String value);
        partial void OnINTERNALL_IPChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> INTERNAL_PORT
        {
            get
            {
                return _INTERNAL_PORT;
            }
            set
            {
                OnINTERNAL_PORTChanging(value);
                ReportPropertyChanging("INTERNAL_PORT");
                _INTERNAL_PORT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INTERNAL_PORT");
                OnINTERNAL_PORTChanged();
            }
        }
        private Nullable<global::System.Int32> _INTERNAL_PORT;
        partial void OnINTERNAL_PORTChanging(Nullable<global::System.Int32> value);
        partial void OnINTERNAL_PORTChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CONNECTIONSTATUSLOG_ID
        {
            get
            {
                return _CONNECTIONSTATUSLOG_ID;
            }
            set
            {
                OnCONNECTIONSTATUSLOG_IDChanging(value);
                ReportPropertyChanging("CONNECTIONSTATUSLOG_ID");
                _CONNECTIONSTATUSLOG_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONNECTIONSTATUSLOG_ID");
                OnCONNECTIONSTATUSLOG_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _CONNECTIONSTATUSLOG_ID;
        partial void OnCONNECTIONSTATUSLOG_IDChanging(Nullable<global::System.Int64> value);
        partial void OnCONNECTIONSTATUSLOG_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LATEST_UPDATE
        {
            get
            {
                return _LATEST_UPDATE;
            }
            set
            {
                OnLATEST_UPDATEChanging(value);
                ReportPropertyChanging("LATEST_UPDATE");
                _LATEST_UPDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATEST_UPDATE");
                OnLATEST_UPDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _LATEST_UPDATE;
        partial void OnLATEST_UPDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnLATEST_UPDATEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="vwSensorDegree")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwSensorDegree : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwSensorDegree 物件。
        /// </summary>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="sENSOR_ID">SENSOR_ID 屬性的初始值。</param>
        /// <param name="iSCONNECTED">ISCONNECTED 屬性的初始值。</param>
        /// <param name="iSVALID">ISVALID 屬性的初始值。</param>
        /// <param name="mFCC_ID">MFCC_ID 屬性的初始值。</param>
        /// <param name="isConfirmed">IsConfirmed 屬性的初始值。</param>
        public static vwSensorDegree CreatevwSensorDegree(global::System.String sITE_ID, global::System.Int32 sENSOR_ID, global::System.String iSCONNECTED, global::System.String iSVALID, global::System.String mFCC_ID, global::System.Boolean isConfirmed)
        {
            vwSensorDegree vwSensorDegree = new vwSensorDegree();
            vwSensorDegree.SITE_ID = sITE_ID;
            vwSensorDegree.SENSOR_ID = sENSOR_ID;
            vwSensorDegree.ISCONNECTED = iSCONNECTED;
            vwSensorDegree.ISVALID = iSVALID;
            vwSensorDegree.MFCC_ID = mFCC_ID;
            vwSensorDegree.IsConfirmed = isConfirmed;
            return vwSensorDegree;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                if (_SITE_ID != value)
                {
                    OnSITE_IDChanging(value);
                    ReportPropertyChanging("SITE_ID");
                    _SITE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SITE_ID");
                    OnSITE_IDChanged();
                }
            }
        }
        private global::System.String _SITE_ID;
        partial void OnSITE_IDChanging(global::System.String value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SENSOR_ID
        {
            get
            {
                return _SENSOR_ID;
            }
            set
            {
                if (_SENSOR_ID != value)
                {
                    OnSENSOR_IDChanging(value);
                    ReportPropertyChanging("SENSOR_ID");
                    _SENSOR_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SENSOR_ID");
                    OnSENSOR_IDChanged();
                }
            }
        }
        private global::System.Int32 _SENSOR_ID;
        partial void OnSENSOR_IDChanging(global::System.Int32 value);
        partial void OnSENSOR_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SENSOR_NAME
        {
            get
            {
                return _SENSOR_NAME;
            }
            set
            {
                OnSENSOR_NAMEChanging(value);
                ReportPropertyChanging("SENSOR_NAME");
                _SENSOR_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SENSOR_NAME");
                OnSENSOR_NAMEChanged();
            }
        }
        private global::System.String _SENSOR_NAME;
        partial void OnSENSOR_NAMEChanging(global::System.String value);
        partial void OnSENSOR_NAMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private Nullable<global::System.Double> _X;
        partial void OnXChanging(Nullable<global::System.Double> value);
        partial void OnXChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y
        {
            get
            {
                return _Y;
            }
            set
            {
                OnYChanging(value);
                ReportPropertyChanging("Y");
                _Y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Y");
                OnYChanged();
            }
        }
        private Nullable<global::System.Double> _Y;
        partial void OnYChanging(Nullable<global::System.Double> value);
        partial void OnYChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISCONNECTED
        {
            get
            {
                return _ISCONNECTED;
            }
            set
            {
                if (_ISCONNECTED != value)
                {
                    OnISCONNECTEDChanging(value);
                    ReportPropertyChanging("ISCONNECTED");
                    _ISCONNECTED = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISCONNECTED");
                    OnISCONNECTEDChanged();
                }
            }
        }
        private global::System.String _ISCONNECTED;
        partial void OnISCONNECTEDChanging(global::System.String value);
        partial void OnISCONNECTEDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ID;
        partial void OnIDChanging(Nullable<global::System.Int32> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EXCUTION_MODE
        {
            get
            {
                return _EXCUTION_MODE;
            }
            set
            {
                OnEXCUTION_MODEChanging(value);
                ReportPropertyChanging("EXCUTION_MODE");
                _EXCUTION_MODE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EXCUTION_MODE");
                OnEXCUTION_MODEChanged();
            }
        }
        private Nullable<global::System.Boolean> _EXCUTION_MODE;
        partial void OnEXCUTION_MODEChanging(Nullable<global::System.Boolean> value);
        partial void OnEXCUTION_MODEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SENSOR_TYPE
        {
            get
            {
                return _SENSOR_TYPE;
            }
            set
            {
                OnSENSOR_TYPEChanging(value);
                ReportPropertyChanging("SENSOR_TYPE");
                _SENSOR_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SENSOR_TYPE");
                OnSENSOR_TYPEChanged();
            }
        }
        private global::System.String _SENSOR_TYPE;
        partial void OnSENSOR_TYPEChanging(global::System.String value);
        partial void OnSENSOR_TYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CURRENT_DEGREE
        {
            get
            {
                return _CURRENT_DEGREE;
            }
            set
            {
                OnCURRENT_DEGREEChanging(value);
                ReportPropertyChanging("CURRENT_DEGREE");
                _CURRENT_DEGREE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CURRENT_DEGREE");
                OnCURRENT_DEGREEChanged();
            }
        }
        private Nullable<global::System.Int32> _CURRENT_DEGREE;
        partial void OnCURRENT_DEGREEChanging(Nullable<global::System.Int32> value);
        partial void OnCURRENT_DEGREEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> VALUE0
        {
            get
            {
                return _VALUE0;
            }
            set
            {
                OnVALUE0Changing(value);
                ReportPropertyChanging("VALUE0");
                _VALUE0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUE0");
                OnVALUE0Changed();
            }
        }
        private Nullable<global::System.Double> _VALUE0;
        partial void OnVALUE0Changing(Nullable<global::System.Double> value);
        partial void OnVALUE0Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> VALUE1
        {
            get
            {
                return _VALUE1;
            }
            set
            {
                OnVALUE1Changing(value);
                ReportPropertyChanging("VALUE1");
                _VALUE1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUE1");
                OnVALUE1Changed();
            }
        }
        private Nullable<global::System.Double> _VALUE1;
        partial void OnVALUE1Changing(Nullable<global::System.Double> value);
        partial void OnVALUE1Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> VALUE2
        {
            get
            {
                return _VALUE2;
            }
            set
            {
                OnVALUE2Changing(value);
                ReportPropertyChanging("VALUE2");
                _VALUE2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VALUE2");
                OnVALUE2Changed();
            }
        }
        private Nullable<global::System.Double> _VALUE2;
        partial void OnVALUE2Changing(Nullable<global::System.Double> value);
        partial void OnVALUE2Changed();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ISVALID
        {
            get
            {
                return _ISVALID;
            }
            set
            {
                if (_ISVALID != value)
                {
                    OnISVALIDChanging(value);
                    ReportPropertyChanging("ISVALID");
                    _ISVALID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ISVALID");
                    OnISVALIDChanged();
                }
            }
        }
        private global::System.String _ISVALID;
        partial void OnISVALIDChanging(global::System.String value);
        partial void OnISVALIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MFCC_ID
        {
            get
            {
                return _MFCC_ID;
            }
            set
            {
                if (_MFCC_ID != value)
                {
                    OnMFCC_IDChanging(value);
                    ReportPropertyChanging("MFCC_ID");
                    _MFCC_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MFCC_ID");
                    OnMFCC_IDChanged();
                }
            }
        }
        private global::System.String _MFCC_ID;
        partial void OnMFCC_IDChanging(global::System.String value);
        partial void OnMFCC_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsConfirmed
        {
            get
            {
                return _IsConfirmed;
            }
            set
            {
                if (_IsConfirmed != value)
                {
                    OnIsConfirmedChanging(value);
                    ReportPropertyChanging("IsConfirmed");
                    _IsConfirmed = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsConfirmed");
                    OnIsConfirmedChanged();
                }
            }
        }
        private global::System.Boolean _IsConfirmed;
        partial void OnIsConfirmedChanging(global::System.Boolean value);
        partial void OnIsConfirmedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="vwSiteToBA_Report")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwSiteToBA_Report : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwSiteToBA_Report 物件。
        /// </summary>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="dATATIME">DATATIME 屬性的初始值。</param>
        /// <param name="tYPE">TYPE 屬性的初始值。</param>
        /// <param name="uRL">URL 屬性的初始值。</param>
        /// <param name="cONTROLLER_ID">CONTROLLER_ID 屬性的初始值。</param>
        /// <param name="mFCC_ID">MFCC_ID 屬性的初始值。</param>
        public static vwSiteToBA_Report CreatevwSiteToBA_Report(global::System.String sITE_ID, global::System.DateTime dATATIME, global::System.String tYPE, global::System.String uRL, global::System.Int32 cONTROLLER_ID, global::System.String mFCC_ID)
        {
            vwSiteToBA_Report vwSiteToBA_Report = new vwSiteToBA_Report();
            vwSiteToBA_Report.SITE_ID = sITE_ID;
            vwSiteToBA_Report.DATATIME = dATATIME;
            vwSiteToBA_Report.TYPE = tYPE;
            vwSiteToBA_Report.URL = uRL;
            vwSiteToBA_Report.CONTROLLER_ID = cONTROLLER_ID;
            vwSiteToBA_Report.MFCC_ID = mFCC_ID;
            return vwSiteToBA_Report;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                if (_SITE_ID != value)
                {
                    OnSITE_IDChanging(value);
                    ReportPropertyChanging("SITE_ID");
                    _SITE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SITE_ID");
                    OnSITE_IDChanged();
                }
            }
        }
        private global::System.String _SITE_ID;
        partial void OnSITE_IDChanging(global::System.String value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATATIME
        {
            get
            {
                return _DATATIME;
            }
            set
            {
                if (_DATATIME != value)
                {
                    OnDATATIMEChanging(value);
                    ReportPropertyChanging("DATATIME");
                    _DATATIME = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DATATIME");
                    OnDATATIMEChanged();
                }
            }
        }
        private global::System.DateTime _DATATIME;
        partial void OnDATATIMEChanging(global::System.DateTime value);
        partial void OnDATATIMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    OnTYPEChanging(value);
                    ReportPropertyChanging("TYPE");
                    _TYPE = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TYPE");
                    OnTYPEChanged();
                }
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                if (_URL != value)
                {
                    OnURLChanging(value);
                    ReportPropertyChanging("URL");
                    _URL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("URL");
                    OnURLChanged();
                }
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ISTOBA
        {
            get
            {
                return _ISTOBA;
            }
            set
            {
                OnISTOBAChanging(value);
                ReportPropertyChanging("ISTOBA");
                _ISTOBA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISTOBA");
                OnISTOBAChanged();
            }
        }
        private Nullable<global::System.Boolean> _ISTOBA;
        partial void OnISTOBAChanging(Nullable<global::System.Boolean> value);
        partial void OnISTOBAChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CONTROLLER_ID
        {
            get
            {
                return _CONTROLLER_ID;
            }
            set
            {
                if (_CONTROLLER_ID != value)
                {
                    OnCONTROLLER_IDChanging(value);
                    ReportPropertyChanging("CONTROLLER_ID");
                    _CONTROLLER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CONTROLLER_ID");
                    OnCONTROLLER_IDChanged();
                }
            }
        }
        private global::System.Int32 _CONTROLLER_ID;
        partial void OnCONTROLLER_IDChanging(global::System.Int32 value);
        partial void OnCONTROLLER_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MFCC_ID
        {
            get
            {
                return _MFCC_ID;
            }
            set
            {
                if (_MFCC_ID != value)
                {
                    OnMFCC_IDChanging(value);
                    ReportPropertyChanging("MFCC_ID");
                    _MFCC_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MFCC_ID");
                    OnMFCC_IDChanged();
                }
            }
        }
        private global::System.String _MFCC_ID;
        partial void OnMFCC_IDChanging(global::System.String value);
        partial void OnMFCC_IDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="vwSiteToBA_Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwSiteToBA_Status : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 vwSiteToBA_Status 物件。
        /// </summary>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="current_degree">current_degree 屬性的初始值。</param>
        public static vwSiteToBA_Status CreatevwSiteToBA_Status(global::System.String sITE_ID, global::System.Int32 current_degree)
        {
            vwSiteToBA_Status vwSiteToBA_Status = new vwSiteToBA_Status();
            vwSiteToBA_Status.SITE_ID = sITE_ID;
            vwSiteToBA_Status.current_degree = current_degree;
            return vwSiteToBA_Status;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                if (_SITE_ID != value)
                {
                    OnSITE_IDChanging(value);
                    ReportPropertyChanging("SITE_ID");
                    _SITE_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SITE_ID");
                    OnSITE_IDChanged();
                }
            }
        }
        private global::System.String _SITE_ID;
        partial void OnSITE_IDChanging(global::System.String value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 current_degree
        {
            get
            {
                return _current_degree;
            }
            set
            {
                if (_current_degree != value)
                {
                    Oncurrent_degreeChanging(value);
                    ReportPropertyChanging("current_degree");
                    _current_degree = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("current_degree");
                    Oncurrent_degreeChanged();
                }
            }
        }
        private global::System.Int32 _current_degree;
        partial void Oncurrent_degreeChanging(global::System.Int32 value);
        partial void Oncurrent_degreeChanged();

        #endregion
    
    }

    #endregion
    
}
