//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ClientTest
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class SSHMC01Entities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'SSHMC01Entities' 區段中找到的連接字串，初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities() : base("name=SSHMC01Entities", "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities(string connectionString) : base(connectionString, "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SSHMC01Entities 物件。
        /// </summary>
        public SSHMC01Entities(EntityConnection connection) : base(connection, "SSHMC01Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUser> tblUser
        {
            get
            {
                if ((_tblUser == null))
                {
                    _tblUser = base.CreateObjectSet<tblUser>("tblUser");
                }
                return _tblUser;
            }
        }
        private ObjectSet<tblUser> _tblUser;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblUser EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUser(tblUser tblUser)
        {
            base.AddObject("tblUser", tblUser);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SSHMC01Model", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUser 物件。
        /// </summary>
        /// <param name="uSER_ID">USER_ID 屬性的初始值。</param>
        public static tblUser CreatetblUser(global::System.String uSER_ID)
        {
            tblUser tblUser = new tblUser();
            tblUser.USER_ID = uSER_ID;
            return tblUser;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                if (_USER_ID != value)
                {
                    OnUSER_IDChanging(value);
                    ReportPropertyChanging("USER_ID");
                    _USER_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USER_ID");
                    OnUSER_IDChanged();
                }
            }
        }
        private global::System.String _USER_ID;
        partial void OnUSER_IDChanging(global::System.String value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_PW
        {
            get
            {
                return _USER_PW;
            }
            set
            {
                OnUSER_PWChanging(value);
                ReportPropertyChanging("USER_PW");
                _USER_PW = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USER_PW");
                OnUSER_PWChanged();
            }
        }
        private global::System.String _USER_PW;
        partial void OnUSER_PWChanging(global::System.String value);
        partial void OnUSER_PWChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_NAME
        {
            get
            {
                return _USER_NAME;
            }
            set
            {
                OnUSER_NAMEChanging(value);
                ReportPropertyChanging("USER_NAME");
                _USER_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USER_NAME");
                OnUSER_NAMEChanged();
            }
        }
        private global::System.String _USER_NAME;
        partial void OnUSER_NAMEChanging(global::System.String value);
        partial void OnUSER_NAMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ROLES
        {
            get
            {
                return _ROLES;
            }
            set
            {
                OnROLESChanging(value);
                ReportPropertyChanging("ROLES");
                _ROLES = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ROLES");
                OnROLESChanged();
            }
        }
        private Nullable<global::System.Int32> _ROLES;
        partial void OnROLESChanging(Nullable<global::System.Int32> value);
        partial void OnROLESChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CUSTOMER_ID
        {
            get
            {
                return _CUSTOMER_ID;
            }
            set
            {
                OnCUSTOMER_IDChanging(value);
                ReportPropertyChanging("CUSTOMER_ID");
                _CUSTOMER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CUSTOMER_ID");
                OnCUSTOMER_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _CUSTOMER_ID;
        partial void OnCUSTOMER_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCUSTOMER_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEPHONE
        {
            get
            {
                return _TELEPHONE;
            }
            set
            {
                OnTELEPHONEChanging(value);
                ReportPropertyChanging("TELEPHONE");
                _TELEPHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEPHONE");
                OnTELEPHONEChanged();
            }
        }
        private global::System.String _TELEPHONE;
        partial void OnTELEPHONEChanging(global::System.String value);
        partial void OnTELEPHONEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MOBLE
        {
            get
            {
                return _MOBLE;
            }
            set
            {
                OnMOBLEChanging(value);
                ReportPropertyChanging("MOBLE");
                _MOBLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MOBLE");
                OnMOBLEChanged();
            }
        }
        private global::System.String _MOBLE;
        partial void OnMOBLEChanging(global::System.String value);
        partial void OnMOBLEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FAX
        {
            get
            {
                return _FAX;
            }
            set
            {
                OnFAXChanging(value);
                ReportPropertyChanging("FAX");
                _FAX = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FAX");
                OnFAXChanged();
            }
        }
        private global::System.String _FAX;
        partial void OnFAXChanging(global::System.String value);
        partial void OnFAXChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_ADDRESS
        {
            get
            {
                return _USER_ADDRESS;
            }
            set
            {
                OnUSER_ADDRESSChanging(value);
                ReportPropertyChanging("USER_ADDRESS");
                _USER_ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USER_ADDRESS");
                OnUSER_ADDRESSChanged();
            }
        }
        private global::System.String _USER_ADDRESS;
        partial void OnUSER_ADDRESSChanging(global::System.String value);
        partial void OnUSER_ADDRESSChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER_MAIL
        {
            get
            {
                return _USER_MAIL;
            }
            set
            {
                OnUSER_MAILChanging(value);
                ReportPropertyChanging("USER_MAIL");
                _USER_MAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USER_MAIL");
                OnUSER_MAILChanged();
            }
        }
        private global::System.String _USER_MAIL;
        partial void OnUSER_MAILChanging(global::System.String value);
        partial void OnUSER_MAILChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URI_CODE
        {
            get
            {
                return _URI_CODE;
            }
            set
            {
                OnURI_CODEChanging(value);
                ReportPropertyChanging("URI_CODE");
                _URI_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URI_CODE");
                OnURI_CODEChanged();
            }
        }
        private global::System.String _URI_CODE;
        partial void OnURI_CODEChanging(global::System.String value);
        partial void OnURI_CODEChanged();

        #endregion
    
    }

    #endregion
    
}
